
title: "Home"
description: >-
  We do research for a better urban system.
theme: minima

url: "https://anduinwang.github.io"
baseurl: "/s3lwebsite"

header_pages:
  - research.md
  - openings.md
  - teaching.md
  - news.md
