
title: "Home"
description: >-
  Sensing, Sustainability & Society Lab
theme: minima

url: "https://anduinwang.github.io"
baseurl: "/s3lwebsite"

header_pages:
  - research.md
  - openings.md
  - teaching.md
  - news.md
