title: "Sensing, Sustainability & Society Lab (S3L)"
description: "Research for a better urban system"
theme: minima

url: "https://anduinwang.github.io"
baseurl: "/s3lwebsite"

header_pages:
  - research.md
  - publications.md
  - openings.md
  - teaching.md
  - cv.md
  - contact.md
  - news.md
